packages/apify/src/autoscaling/autoscaled_pool.ts
packages/apify/src/autoscaling/snapshotter.ts
packages/apify/src/browser_launchers/browser_launcher.ts
packages/apify/src/browser_launchers/playwright_launcher.ts
packages/apify/src/browser_launchers/puppeteer_launcher.ts
packages/apify/src/enqueue_links/click_elements.ts
packages/apify/src/enqueue_links/enqueue_links.ts
packages/apify/src/enqueue_links/shared.ts
packages/apify/src/session_pool/session.ts
packages/apify/src/session_pool/session_pool.ts
packages/apify/src/stealth/stealth.ts
packages/apify/src/storages/dataset.ts
packages/apify/src/storages/key_value_store.ts
packages/apify/src/storages/request_queue.ts
packages/apify/src/storages/storage_manager.ts
test/storages/key_value_store.test.ts
test/storages/request_queue.test.ts

Second portion of TS type definitions, jsdoc cleaned up + updated the tests where necessary.
Main question I have here is related to the dataset. There's `DatasetDataOptions` interface, which has all params like `limit`, `skipHidden`, `fields` and so on. And there are methods such as `forEach` and some others. `forEach` has 3 options exposed (desc, fields, unwind). While inside of the method there are checks for `format`, `limit`, maybe some others. So I could basically use the `DatasetDataOptions` interface there, but in order to hide some params, I am using `DatasetIteratorOptions extends DatasetDataOptions` with some params overridden with `@internal`. Is it the correct way to do it or what's the proper way in such cases?
P.S.: sry for the delay, will start with the remaining part …

chore: add more ts type definitions

---

packages/apify/src/actor.ts
packages/apify/src/apify.ts
packages/apify/src/configuration.ts
packages/apify/src/proxy_configuration.ts
packages/apify/src/pseudo_url.ts
packages/apify/src/puppeteer_request_interception.ts
packages/apify/src/puppeteer_utils.ts
packages/apify/src/request.ts
packages/apify/src/request_list.ts
packages/apify/src/storages/request_queue.ts
packages/apify/src/utils.ts
packages/apify/src/utils_request.ts
packages/apify/src/utils_social.ts
test/request.test.ts

Last batch of types updates.
1. I skipped `utils_log.ts`, it's mentioned that it's for building docs mainly. Should I update `types-apify/apify-shared/log.d.ts` instead, or I could just skip it indeed?
2. Tests should be passing, but I would ask you to kinda double check the `configuration.ts` and `request.ts` (`pushErrorMessage` specifically).
3. `utils_request.ts` - I am kinda confused about this one - there seems to be some mess with types (it's not finished). Should I have `GotScrapingOptions` as an interface here? There's also some mismatch between `stream.Duplex` vs `CancelableRequest` (there was also a TODO about it). Could you point me to what's kinda the right approach here or should I also skip it for now?
4. `request.test.ts` - there's one test failing on …

chore: add more TS types (last batch)

---

CHANGELOG.md

`Apify.metamorph` calls client's `metamorph`, not `call`

chore: correct shortcut explanation

---

test/actor-scrapper/scraper-tools/browser_tools.test.ts
test/apify/actor.test.ts
test/apify/autoscaling/autoscaled_pool.test.ts
test/apify/browser_launchers/playwright_launcher.test.ts
test/apify/browser_launchers/puppeteer_launcher.test.ts
test/apify/crawlers/basic_crawler.test.ts
test/apify/request_list.test.ts

`sinon` and `underscore` were removed from the tests.
It seems that Sinon is more capable (and less verbose) than Jest, but the base idea behind the tests should stay the same.

chore: test update (sinon + underscore)

---

package-lock.json
package.json
packages/apify/src/actor.ts
packages/basic-crawler/src/internals/basic-crawler.ts
packages/core/src/autoscaling/system_status.ts
packages/core/src/enqueue_links/enqueue_links.ts
packages/scraper-tools/src/run_actor.ts
test/apify/actor.test.ts
test/apify/apify.test.ts
test/apify/crawlers/basic_crawler.test.ts
test/e2e/test-che-default/test.mjs

- `BasicCrawler.run()` now returns final statistics
- `Actor.main()` now returns promise, so it can be awaited (still throws synchronously for validation)
- `Actor.main()` is now generic and is typed to return the same as the `UserFunc` callback returns
- ~new method `Actor.run` that calls `crawler.run()` inside `Actor.main` for easier testing~
- fixes `enqueueLinks` default strategy being applied even with explicit pseudoUrls
- fixes creating crawlers with implicit `RequestQueue`

refactor: make `Actor.main()` awaitable and rework one E2E test as an example

---

CHANGELOG.md
packages/actor-scraper/cheerio-scraper/src/internals/crawler_setup.ts
packages/cheerio-crawler/src/internals/cheerio-crawler.ts
test/apify/crawlers/cheerio_crawler.test.ts

BREAKING CHANGE:
`prepareRequestFunction` and `postResponseFunction` options are removed, use navigation hooks instead.

refactor: remove `prepareRequestFunction` and `postResponseFunction`

---

docs/examples/basic_crawler.mdx
docs/examples/playwright_crawler.ts
docs/examples/puppeteer_crawler.ts
docs/guides/apify_platform.mdx
docs/guides/environment_variables.mdx
docs/guides/getting_started.mdx
docs/guides/motivation.mdx
docs/guides/proxy_management.mdx
docs/guides/quick_start.mdx
docs/guides/request_storage.mdx
docs/guides/result_storage.mdx
docs/guides/session_management.mdx
docs/guides/typescript_actor.mdx
docs/readme/introduction.md
docs/readme/overview.md
docs/readme/support.md
docs/upgrading/upgrading_v1.md

Following a [PR comment from the past](https://github.com/apify/apify-ts/pull/71#discussion_r849309797), documentation is updated with the new library name.
This does not affect the package name in commands or any URLs, only what has been captured with `(the )?Apify SDK`.

docs: Apify SDK to Crawlee

---

packages/utils/src/internals/general.ts
test/utils/general.test.ts

This PR fixes the usage of  `{ purge: true }` param of `Actor.main()`. Currently using `{ purge: true }` will lead to the removal of everything inside of the `apify_storage` folder, while it should only remove default storage folders contents (besides `INPUT.json` file), i.e. mimic `apify run -p`.
Closes #102.
Ready for review, but do not merge it yet, also need to update the tests.

fix: update purgeLocalStorage function to mimic 'purge' param of 'apify run'

---

packages/apify/src/actor.ts
packages/apify/src/platform_event_manager.ts
packages/core/src/events/event_manager.ts
packages/core/src/events/local_event_manager.ts
test/apify/actor.test.ts

- adds `statusMessage` option (object as first param works too)
- adds `exit` event
- adds `timeoutSecs` option to wait before calling `process.exit`
source: https://github.com/apify/actor-specs#exit-actor

feat: refactor `Actor.exit` to conform to actor specs

---

test/e2e/cheerio-enqueue-links/actor/main.js
test/e2e/cheerio-max-requests/actor/main.js
test/e2e/cheerio-max-requests/test.mjs
test/e2e/playwright-default/test.mjs
test/e2e/proxy-rotation/test.mjs
test/e2e/puppeteer-default/test.mjs
test/e2e/puppeteer-enqueue-links/actor/main.js
test/e2e/puppeteer-enqueue-links/test.mjs
test/e2e/puppeteer-ignore-ssl-errors/test.mjs
test/e2e/puppeteer-initial-cookies/test.mjs
test/e2e/puppeteer-page-info/test.mjs
test/e2e/puppeteer-store-pagination-jquery/actor/main.js
test/e2e/puppeteer-store-pagination-jquery/test.mjs
test/e2e/puppeteer-store-pagination/actor/main.js
test/e2e/puppeteer-store-pagination/test.mjs
test/e2e/puppeteer-throw-on-ssl-errors/test.mjs
test/e2e/run.mjs

- Lowered max number of requests for pagination tests.
- provided specific selector for enqueueLinks tests + limited number of requests there.
Each test out of what we have now should finish with ~1m tops locally.
Will update memory for platform tests + would wait before at least one full e2e run will finish before merging.

test: optimise some e2e tests

---

docs/examples/accept_user_input.mdx
docs/examples/add_data_to_dataset.mdx
docs/examples/basic_crawler.mdx
docs/examples/basic_crawler.ts
docs/examples/cheerio_crawler.mdx
docs/examples/cheerio_crawler.ts
docs/examples/crawl_all_links.mdx
docs/examples/crawl_multiple_urls.mdx
docs/examples/crawl_relative_links.mdx
docs/examples/crawl_sitemap.mdx
docs/examples/crawl_some_links.mdx
docs/examples/crawl_some_links.ts
docs/examples/forms.mdx
docs/examples/map.ts
docs/examples/map_and_reduce.mdx
docs/examples/playwright_crawler.mdx
docs/examples/puppeteer_capture_screenshot.mdx
docs/examples/puppeteer_crawler.mdx
docs/examples/puppeteer_crawler_crawler_utils_snapshot.ts
docs/examples/puppeteer_recursive_crawl.ts
docs/examples/puppeteer_with_proxy.ts
docs/examples/reduce.ts
docs/guides/avoid_blocking.mdx
docs/guides/getting_started.mdx
docs/guides/motivation.mdx
docs/guides/quick_start.mdx
packages/core/src/enqueue_links/enqueue_links.ts
website/src/components/Highlights.jsx
website/src/css/customTheme.css
website/src/pages/index.js

This is part one which mostly focuses on enqueueLink as well as cleaning up examples/guides
A future PR will come for Request.skipNavigation

docs: cleanup examples and make them more accurate

---

docs/guides/avoid_blocking.mdx
docs/guides/docker_images.mdx
docs/guides/docker_images_js
docs/guides/docker_images_ts
docs/guides/proxy_management.mdx
docs/guides/proxy_management_inspection_cheerio.ts
docs/guides/proxy_management_inspection_playwright.ts
docs/guides/proxy_management_inspection_puppeteer.ts
docs/guides/proxy_management_integration_cheerio.ts
docs/guides/proxy_management_integration_playwright.ts
docs/guides/proxy_management_integration_puppeteer.ts
docs/guides/proxy_management_session_cheerio.ts
docs/guides/proxy_management_session_playwright.ts
docs/guides/proxy_management_session_puppeteer.ts
docs/guides/proxy_management_session_standalone.ts

@B4nan could you please a quick look?
In the docker images - I felt like we should mention the multi-stage build for TS projects.
Proxy management - there was a mention of Apify proxy already, and I am not sure how we should proceed. Now I basically added more info on two options (using Apify proxy vs using own proxies). On one hand - it's about proxy and it should all be there. On the other hand - if we want to separate Apify and Crawlee - maybe it qualifies for "more verbose platfrom guide". But on the other hand - it's not really about the platform, it could also be used locally, but requires the usage of Actor class (and thus apify package). Maybe there shold even be another guide - about using the Actor class locally (proxy, storages etc). What do you think?

docs: update docker images + proxy management guides

---

test/e2e/run.mjs
test/e2e/tools.mjs

PLATFORM e2e tests take significantly more time than local/memory storage ones mainly due to actor build, now we'll have a link to build log with build time + view run link with actual run time (without build time).
CI run [here](https://github.com/apify/apify-ts/runs/6758395569?check_suite_focus=true).
I was also annoyed by missing spaces in logs - it somehow ignores the space after the `colors[color]` is used it seems, so moved the space inside `colors[color]` calls - kinda shitty solution, but at least I am not triggered every time now =D

test: add platform links to e2e tests

---

packages/basic-crawler/src/internals/basic-crawler.ts
packages/browser-crawler/src/internals/browser-crawler.ts
packages/cheerio-crawler/src/internals/cheerio-crawler.ts
packages/core/src/index.ts
packages/core/src/router.ts
packages/playwright-crawler/src/internals/playwright-crawler.ts
packages/puppeteer-crawler/src/internals/puppeteer-crawler.ts
test/core/router.test.ts
test/e2e/cheerio-page-info/actor/main.js
test/e2e/puppeteer-store-pagination/actor/main.js
website/src/pages/index.js

Simple router that works based on request labels. This instance can then serve as a `requestHandler` of your crawler.
```ts
import { Router, CheerioCrawler, CheerioCrawlingContext } from '@crawlee/cheerio';
const router = Router.create<CheerioCrawlingContext>();
// we can also use factory methods for specific crawling contexts, the above equals to:
// import { createCheerioRouter } from '@crawlee/cheerio';
// const router = createCheerioRouter();
router.addHandler('label-a', async (ctx) => {
ctx.log.info('...');
});
router.addDefaultHandler(async (ctx) => {
ctx.log.info('...');
});
const crawler = new CheerioCrawler({
requestHandler: router,
});
await crawler.run();
```
Alternatively we can use the default router instance from crawler object:
```ts
import { CheerioCrawler } from …
```

feat: add `Router`

---

packages/memory-storage/test/write-metadata.test.ts

Fixes https://github.com/apify/apify-ts/pull/138#issuecomment-1156672074
Since the worker can take a while to actually write the files, a set timeout might not be sufficient (especially if overloaded). Now the test will keep trying to access the dir (since we know it should be created) before running tests on it

chore: fix flaky memory storage test

---

package-lock.json
packages/apify/package.json
packages/apify/src/actor.ts
packages/core/package.json
packages/core/src/events/event_manager.ts
test/apify/events.test.ts

To achieve this in the cleanest way possible (and to also make this usable by anyone who might need this), I took the EventEmitter interface from nodejs, replicated it in more modern code, added support for awaiting the execution of all listeners, and made it its own module.
There's no difference otherwise. The code does (almost) the exact same things the nodejs core code does (bar the catch handling for promises: the rejections will always be handled and emitted as error events).

chore: await all event listener executions before exiting

---

packages/browser-crawler/src/internals/browser-crawler.ts
packages/playwright-crawler/src/internals/playwright-crawler.ts

closes #113 
PlaywrightCrawler and PuppeteerCrawler behavior standardized. Specifying `launchContext.userAgent` overrides the `browserPool.useFingerprints` setting - the warning message only shows when `browserPool.useFingerprints` is set, though.

fix: `userAgent` overrides `useFingerprints`

---

docs/examples/skip-navigation.mdx
docs/examples/skip-navigation.ts
docs/upgrading/upgrading_v3.md

I didn't know if I should have created an even simpler presentation in the upgrading guide or if just linking to the example is enough...so I went with just linking as it felt more appropriate

docs: add skip-navigation example

---

packages/basic-crawler/src/internals/basic-crawler.ts
packages/browser-crawler/src/internals/browser-crawler.ts
packages/cheerio-crawler/src/internals/cheerio-crawler.ts
packages/core/src/crawlers/crawler_commons.ts
packages/playwright-crawler/src/internals/playwright-crawler.ts
test/core/crawlers/basic_crawler.test.ts
test/core/crawlers/browser_crawler.test.ts
test/core/crawlers/cheerio_crawler.test.ts

I know that I need to add it to Cheerio and other crawlers, but could you have a quick look before I proceed with the rest?
Also thinking - maybe it's worth adding helper `crawler.reclaimRequest()` since with user-provided function for requests to be retried - they would need to either manually do it or just skip it. Or thinking about it now - maybe there should be something like `context.reclainRequest` (which would be `true` by default) and otherwise user would need to set it to false and thus it would be marked as handled)?

feat: add error handler for requests to be retried

---

CHANGELOG.md
docs/upgrading/upgrading_v3.md
package-lock.json
packages/browser-pool/src/browser-pool.ts
packages/browser-pool/src/index.ts
packages/browser-pool/test/changing-page-options.test.ts
packages/browser-pool/test/multiple-plugins.test.ts
packages/browser-pool/test/no-hybrid-plugins.test.ts
packages/browser-pool/test/proxy-sugar.test.ts
packages/playwright-crawler/src/internals/playwright-crawler.ts
packages/puppeteer-crawler/src/internals/puppeteer-crawler.ts
test/browser-pool/browser-pool.test.ts

Closes #156 
Makes the browser-pool ensure that the constructor of the first plugin is whats used for all provided plugins (making it compatible with user-provided plugins too...should there be any)

feat: prevent hybrid plugins from being used with browser-pool

---

docs/guides/apify_platform.mdx
docs/guides/avoid_blocking.mdx
docs/guides/avoid_blocking_playwright.ts
docs/guides/avoid_blocking_playwright_fingerprints_off.ts
docs/guides/avoid_blocking_puppeteer.ts
docs/guides/avoid_blocking_puppeteer_fingerprints_off.ts
docs/guides/docker_images_js
docs/guides/quick_start.mdx
docs/guides/quick_start_cheerio.log
website/docusaurus.config.js

- fix apify console links in `apify-platform`
- fix links to docker guide in `docker-images`: instead of sdk.apify.com -> use crawlee.dev
- update `avoid-blocking` guide
- `quick-start` - instead of the gif for cheerio - added static log example + kept the same gif for playwright/puppeteer + added a sentence before gif/log. I think it should be ok but let me know if you think it's not.
Last thing to do on my list here is to update the `apify-platform` guide with links to new repo, so will do in another PR once `apify-sdk-js` is live.

docs: few more updates to guides
